### PR TITLE
fix(scanner): scan lockfiles

### LINKED ISSUE #2207: failed to scan lockfile in pseudo server on windows
```powershell
PS C:\Users\vagrant> cmd.exe /c 'curl.exe -sL https://github.com/future-architect/vuls/releases/download/v0.31.1/vuls_0.31.1_windows_amd64.tar.gz | tar.exe zxf - vuls.exe'

PS C:\Users\vagrant> @"
version = "v2"

[default]

[servers]

[servers.pseudo]
type = "pseudo"
lockfiles = ["C:\\Users\\vagrant\\Downloads\\package-lock.json"]
"@ | Set-Content config.toml

PS C:\Users\vagrant> curl.exe -sL --create-dirs --output Downloads\package-lock.json https://raw.githubusercontent.com/vulsio/integration/refs/heads/main/data/lockfile/npm-v3/package-lock.json

PS C:\Users\vagrant> .\vuls.exe scan
time="May 15 00:41:06" level=info msg="vuls-0.31.1-a9ff663ea8fd7f42583dac66afdac63bd3b85f54-2025-05-08T09:09:29Z" 
time="May 15 00:41:06" level=info msg="Start scanning"
time="May 15 00:41:06" level=info msg="config: C:\\Users\\vagrant\\config.toml"
time="May 15 00:41:06" level=info msg="Validating config..."
time="May 15 00:41:06" level=info msg="Detecting Server/Container OS... "
time="May 15 00:41:06" level=info msg="Detecting OS of servers... "
time="May 15 00:41:06" level=info msg="(1/1) Detected: pseudo: pseudo "
time="May 15 00:41:06" level=info msg="Detecting OS of containers... "
time="May 15 00:41:06" level=info msg="Checking Scan Modes... "
time="May 15 00:41:06" level=info msg="Detecting Platforms... "
time="May 15 00:41:06" level=info msg="(1/1) pseudo is running on other"
time="May 15 00:41:06" level=info msg="Scanning listen port..."
time="May 15 00:41:06" level=info msg="Using Port Scanner: Vuls built-in Scanner"
time="May 15 00:41:06" level=info msg="Scanning Language-specific Packages..."
time="May 15 00:41:06" level=error msg="Error on pseudo, err: [Failed to scan Library:\n    github.com/future-architect/vuls/scanner.Scanner.getScanResults.func1\n        github.com/future-architect/vuls/scanner/scanner.go:981\n  - Failed to create link. err:\n    github.com/future-architect/vuls/scanner.AnalyzeLibrary\n        github.com/future-architect/vuls/scanner/base.go:787\n  - mapfs write error:\n    github.com/aquasecurity/trivy/pkg/fanal/analyzer.(*CompositeFS).CreateLink\n        github.com/aquasecurity/trivy@v0.61.0/pkg/fanal/analyzer/fs.go:82\n  - file does not exist]"


Scan Summary
================
pseudo  Error           Use configtest subcommand or scan with --debug to view the details


time="May 15 00:41:06" level=error msg="Failed to scan: Failed to scan. err:\n    github.com/future-architect/vuls/scanner.Scanner.Scan\n        github.com/future-architect/vuls/scanner/scanner.go:111\n  - An error occurred on [pseudo]"
```

### PR DESCRIPTION
**Pull request by MaineK00n**
If this Pull Request is work in progress, Add a prefix of “[WIP]” in the title.

# What did you implement:

Fixes #2207 #2208 #2209 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
### setup
```console
$ curl -sL --create-dirs --output Downloads/package-lock.json https://raw.githubusercontent.com/vulsio/integration/refs/heads/main/data/lockfile/npm-v3/package-lock.json
```

### abspath
```console
$ cat << EOS > config.toml
version = "v2"

[default]

[servers]

[servers.lockfile]
type = "pseudo"
scanMode           = ["fast"]
scanModules        = ["lockfile"]
lockfiles = ["/home/vagrant/Downloads/package-lock.json"]
EOS

$ ./vuls scan
[May 18 21:12:59]  INFO [localhost] vuls-v0.32.0-build-20250519_061016_916f9da
[May 18 21:12:59]  INFO [localhost] Start scanning
[May 18 21:12:59]  INFO [localhost] config: /home/vagrant/config.toml
[May 18 21:12:59]  INFO [localhost] Validating config...
[May 18 21:12:59]  INFO [localhost] Detecting Server/Container OS... 
[May 18 21:12:59]  INFO [localhost] Detecting OS of servers... 
[May 18 21:12:59]  INFO [localhost] (1/1) Detected: lockfile: pseudo 
[May 18 21:12:59]  INFO [localhost] Detecting OS of containers... 
[May 18 21:12:59]  INFO [localhost] Checking Scan Modes... 
[May 18 21:12:59]  INFO [localhost] Detecting Platforms... 
[May 18 21:12:59]  INFO [localhost] (1/1) lockfile is running on other
[May 18 21:12:59]  INFO [lockfile] Scanning Language-specific Packages...
2025-05-18T21:12:59Z	INFO	[npm] To collect the license information of packages, "npm install" needs to be performed beforehand	dir="home/vagrant/Downloads/node_modules"


Scan Summary
================
lockfile	pseudo	0 installed, 0 updatable	250 libs





To view the detail, vuls tui is useful.
To send a report, run vuls report -h.
```

### relpath
```console
$ cat << EOS > config.toml
version = "v2"

[default]

[servers]

[servers.lockfile]
type = "pseudo"
scanMode           = ["fast"]
scanModules        = ["lockfile"]
lockfiles = ["Downloads/package-lock.json"]
EOS

$ ./vuls scan
[May 18 21:13:17]  INFO [localhost] vuls-v0.32.0-build-20250519_061016_916f9da
[May 18 21:13:17]  INFO [localhost] Start scanning
[May 18 21:13:17]  INFO [localhost] config: /home/vagrant/config.toml
[May 18 21:13:17]  INFO [localhost] Validating config...
[May 18 21:13:17]  INFO [localhost] Detecting Server/Container OS... 
[May 18 21:13:17]  INFO [localhost] Detecting OS of servers... 
[May 18 21:13:17]  INFO [localhost] (1/1) Detected: lockfile: pseudo 
[May 18 21:13:17]  INFO [localhost] Detecting OS of containers... 
[May 18 21:13:17]  INFO [localhost] Checking Scan Modes... 
[May 18 21:13:17]  INFO [localhost] Detecting Platforms... 
[May 18 21:13:17]  INFO [localhost] (1/1) lockfile is running on other
[May 18 21:13:17]  INFO [lockfile] Scanning Language-specific Packages...
2025-05-18T21:13:17Z	INFO	[npm] To collect the license information of packages, "npm install" needs to be performed beforehand	dir="home/vagrant/Downloads/node_modules"


Scan Summary
================
lockfile	pseudo	0 installed, 0 updatable	250 libs





To view the detail, vuls tui is useful.
To send a report, run vuls report -h.
```

### findlock
```console
$ cat << EOS > config.toml
version = "v2"

[default]

[servers]

[servers.lockfile]
type = "pseudo"
scanMode           = ["fast"]
scanModules        = ["lockfile"]
findLock = true
findLockDirs = ["/home/vagrant/Downloads"]
EOS

$ ./vuls scan
[May 18 21:13:37]  INFO [localhost] vuls-v0.32.0-build-20250519_061016_916f9da
[May 18 21:13:37]  INFO [localhost] Start scanning
[May 18 21:13:37]  INFO [localhost] config: /home/vagrant/config.toml
[May 18 21:13:37]  INFO [localhost] Validating config...
[May 18 21:13:37]  INFO [localhost] Detecting Server/Container OS... 
[May 18 21:13:37]  INFO [localhost] Detecting OS of servers... 
[May 18 21:13:37]  INFO [localhost] (1/1) Detected: lockfile: pseudo 
[May 18 21:13:37]  INFO [localhost] Detecting OS of containers... 
[May 18 21:13:37]  INFO [localhost] Checking Scan Modes... 
[May 18 21:13:37]  INFO [localhost] Detecting Platforms... 
[May 18 21:13:37]  INFO [localhost] (1/1) lockfile is running on other
[May 18 21:13:37]  INFO [lockfile] Scanning Language-specific Packages...
[May 18 21:13:37] ERROR [localhost] Error on lockfile, err: [Failed to scan Library:
    github.com/future-architect/vuls/scanner.Scanner.getScanResults.func1
        github.com/future-architect/vuls/scanner/scanner.go:981
  - FindLock is not supported in pseudo:
    github.com/future-architect/vuls/scanner.(*pseudo).scanLibraries
        github.com/future-architect/vuls/scanner/pseudo.go:95]


Scan Summary
================
lockfile	Error		Use configtest subcommand or scan with --debug to view the details


[May 18 21:13:37] ERROR [localhost] Failed to scan: Failed to scan. err:
    github.com/future-architect/vuls/scanner.Scanner.Scan
        github.com/future-architect/vuls/scanner/scanner.go:111
  - An error occurred on [lockfile]
```

### setup
```console
PS C:\Users\vagrant> curl.exe -sL --create-dirs --output Downloads\package-lock.json https://raw.githubusercontent.com/vulsio/integration/refs/heads/main/data/lockfile/npm-v3/package-lock.json
```

### abspath
```powershell
PS C:\Users\vagrant> @"
version = "v2"

[default]

[servers]

[servers.lockfile]
type = "pseudo"
scanMode           = ["fast"]
scanModules        = ["lockfile"]
lockfiles = ["C:\\Users\\vagrant\\Downloads\\package-lock.json"]
"@ | Set-Content config.toml

PS C:\Users\vagrant> .\vuls.exe scan
time="May 18 21:19:26" level=info msg="vuls-v0.32.0-build-20250519_061025_916f9da" 
time="May 18 21:19:26" level=info msg="Start scanning" 
time="May 18 21:19:26" level=info msg="config: C:\\Users\\vagrant\\config.toml" 
time="May 18 21:19:26" level=info msg="Validating config..." 
time="May 18 21:19:26" level=info msg="Detecting Server/Container OS... " 
time="May 18 21:19:26" level=info msg="Detecting OS of servers... " 
time="May 18 21:19:26" level=info msg="(1/1) Detected: lockfile: pseudo " 
time="May 18 21:19:26" level=info msg="Detecting OS of containers... " 
time="May 18 21:19:26" level=info msg="Checking Scan Modes... " 
time="May 18 21:19:26" level=info msg="Detecting Platforms... " 
time="May 18 21:19:26" level=info msg="(1/1) lockfile is running on other" 
time="May 18 21:19:26" level=info msg="Scanning Language-specific Packages..." 
2025-05-18T21:19:26Z    INFO    [npm] To collect the license information of packages, "npm install" needs to be performed beforehand    dir="C/Users/vagrant/Downloads/node_modules"


Scan Summary
================
lockfile        pseudo  0 installed, 0 updatable        250 libs





To view the detail, vuls tui is useful.
To send a report, run vuls report -h.

```

### relpath
```powershell
PS C:\Users\vagrant> @"
version = "v2"

[default]

[servers]

[servers.lockfile]
type = "pseudo"
scanMode           = ["fast"]
scanModules        = ["lockfile"]
lockfiles = ["Downloads\\package-lock.json"]
"@ | Set-Content config.toml

PS C:\Users\vagrant> .\vuls.exe scan
time="May 18 21:19:42" level=info msg="vuls-v0.32.0-build-20250519_061025_916f9da" 
time="May 18 21:19:42" level=info msg="Start scanning" 
time="May 18 21:19:42" level=info msg="config: C:\\Users\\vagrant\\config.toml" 
time="May 18 21:19:42" level=info msg="Validating config..." 
time="May 18 21:19:42" level=info msg="Detecting Server/Container OS... " 
time="May 18 21:19:42" level=info msg="Detecting OS of servers... " 
time="May 18 21:19:42" level=info msg="(1/1) Detected: lockfile: pseudo " 
time="May 18 21:19:42" level=info msg="Detecting OS of containers... " 
time="May 18 21:19:42" level=info msg="Checking Scan Modes... " 
time="May 18 21:19:42" level=info msg="Detecting Platforms... " 
time="May 18 21:19:42" level=info msg="(1/1) lockfile is running on other" 
time="May 18 21:19:42" level=info msg="Scanning Language-specific Packages..." 
2025-05-18T21:19:42Z    INFO    [npm] To collect the license information of packages, "npm install" needs to be performed beforehand    dir="C/Users/vagrant/Downloads/node_modules"


Scan Summary
================
lockfile        pseudo  0 installed, 0 updatable        250 libs





To view the detail, vuls tui is useful.
To send a report, run vuls report -h.
```

### findlock
```powershell
PS C:\Users\vagrant> @"
version = "v2"

[default]

[servers]

[servers.lockfile]
type = "pseudo"
findLock = true
scanMode           = ["fast"]
scanModules        = ["lockfile"]
findLockDirs = ["C:\\Users\\vagrant\\Downloads"]
"@ | Set-Content config.toml

PS C:\Users\vagrant> .\vuls.exe scan
time="May 18 21:20:01" level=info msg="vuls-v0.32.0-build-20250519_061025_916f9da" 
time="May 18 21:20:01" level=info msg="Start scanning" 
time="May 18 21:20:01" level=info msg="config: C:\\Users\\vagrant\\config.toml"
time="May 18 21:20:01" level=info msg="Validating config..."
time="May 18 21:20:01" level=info msg="Detecting Server/Container OS... "
time="May 18 21:20:01" level=info msg="Detecting OS of servers... "
time="May 18 21:20:01" level=info msg="(1/1) Detected: lockfile: pseudo "
time="May 18 21:20:01" level=info msg="Detecting OS of containers... "
time="May 18 21:20:01" level=info msg="Checking Scan Modes... "
time="May 18 21:20:01" level=info msg="Detecting Platforms... "
time="May 18 21:20:01" level=info msg="(1/1) lockfile is running on other"
time="May 18 21:20:01" level=info msg="Scanning Language-specific Packages..."
time="May 18 21:20:01" level=error msg="Error on lockfile, err: [Failed to scan Library:\n    github.com/future-architect/vuls/scanner.Scanner.getScanResults.func1\n        github.com/future-architect/vuls/scanner/scanner.go:981\n  - FindLock is not supported in pseudo:\n    github.com/future-architect/vuls/scanner.(*pseudo).scanLibraries\n        github.com/future-architect/vuls/scanner/pseudo.go:95]"


Scan Summary
================
lockfile        Error           Use configtest subcommand or scan with --debug to view the details


time="May 18 21:20:01" level=error msg="Failed to scan: Failed to scan. err:\n    github.com/future-architect/vuls/scanner.Scanner.Scan\n        github.com/future-architect/vuls/scanner/scanner.go:111\n  - An error occurred on [lockfile]"
```

### setup
```console
$ curl -sL --create-dirs --output Downloads/package-lock.json https://raw.githubusercontent.com/vulsio/integration/refs/heads/main/data/lockfile/npm-v3/package-lock.json
```

### abspath
```powershell
$ cat << EOS > config.toml
version = "v2"

[default]

[servers]

[servers.lockfile]
host = "localhost"
port = "local"
scanMode           = ["fast"]
scanModules        = ["lockfile"]
lockfiles = ["/home/vagrant/Downloads/package-lock.json"]
EOS

$ ./vuls scan
[May 18 21:14:20]  INFO [localhost] vuls-v0.32.0-build-20250519_061016_916f9da
[May 18 21:14:20]  INFO [localhost] Start scanning
[May 18 21:14:20]  INFO [localhost] config: /home/vagrant/config.toml
[May 18 21:14:20]  INFO [localhost] Validating config...
[May 18 21:14:20]  INFO [localhost] Detecting Server/Container OS... 
[May 18 21:14:20]  INFO [localhost] Detecting OS of servers... 
[May 18 21:14:20]  INFO [localhost] (1/1) Detected: lockfile: ubuntu 24.04
[May 18 21:14:20]  INFO [localhost] Detecting OS of containers... 
[May 18 21:14:20]  INFO [localhost] Checking Scan Modes... 
[May 18 21:14:20]  INFO [localhost] Detecting Platforms... 
[May 18 21:14:22]  INFO [localhost] (1/1) lockfile is running on other
[May 18 21:14:22]  INFO [lockfile] Scanning Language-specific Packages...
2025-05-18T21:14:22Z	INFO	[npm] To collect the license information of packages, "npm install" needs to be performed beforehand	dir="home/vagrant/Downloads/node_modules"


Scan Summary
================
lockfile	ubuntu24.04	0 installed	250 libs





To view the detail, vuls tui is useful.
To send a report, run vuls report -h.
```

### relpath
```powershell
$ cat << EOS > config.toml
version = "v2"

[default]

[servers]

[servers.lockfile]
host = "localhost"
port = "local"
scanMode           = ["fast"]
scanModules        = ["lockfile"]
lockfiles = ["Downloads/package-lock.json"]
EOS

$ ./vuls scan
[May 18 21:14:47]  INFO [localhost] vuls-v0.32.0-build-20250519_061016_916f9da
[May 18 21:14:47]  INFO [localhost] Start scanning
[May 18 21:14:47]  INFO [localhost] config: /home/vagrant/config.toml
[May 18 21:14:47]  INFO [localhost] Validating config...
[May 18 21:14:47]  INFO [localhost] Detecting Server/Container OS... 
[May 18 21:14:47]  INFO [localhost] Detecting OS of servers... 
[May 18 21:14:47]  INFO [localhost] (1/1) Detected: lockfile: ubuntu 24.04
[May 18 21:14:47]  INFO [localhost] Detecting OS of containers... 
[May 18 21:14:47]  INFO [localhost] Checking Scan Modes... 
[May 18 21:14:47]  INFO [localhost] Detecting Platforms... 
[May 18 21:14:49]  INFO [localhost] (1/1) lockfile is running on other
[May 18 21:14:49]  INFO [lockfile] Scanning Language-specific Packages...
2025-05-18T21:14:49Z	INFO	[npm] To collect the license information of packages, "npm install" needs to be performed beforehand	dir="home/vagrant/Downloads/node_modules"


Scan Summary
================
lockfile	ubuntu24.04	0 installed	250 libs





To view the detail, vuls tui is useful.
To send a report, run vuls report -h.
```

### findlock
```powershell
$ cat << EOS > config.toml
version = "v2"

[default]

[servers]

[servers.lockfile]
host = "localhost"
port = "local"
scanMode           = ["fast"]
scanModules        = ["lockfile"]
findLock = true
findLockDirs = ["/home/vagrant/Downloads"]
EOS

$ ./vuls scan
[May 18 21:15:07]  INFO [localhost] vuls-v0.32.0-build-20250519_061016_916f9da
[May 18 21:15:07]  INFO [localhost] Start scanning
[May 18 21:15:07]  INFO [localhost] config: /home/vagrant/config.toml
[May 18 21:15:07]  INFO [localhost] Validating config...
[May 18 21:15:07]  INFO [localhost] Detecting Server/Container OS... 
[May 18 21:15:07]  INFO [localhost] Detecting OS of servers... 
[May 18 21:15:07]  INFO [localhost] (1/1) Detected: lockfile: ubuntu 24.04
[May 18 21:15:07]  INFO [localhost] Detecting OS of containers... 
[May 18 21:15:07]  INFO [localhost] Checking Scan Modes... 
[May 18 21:15:07]  INFO [localhost] Detecting Platforms... 
[May 18 21:15:09]  INFO [localhost] (1/1) lockfile is running on other
[May 18 21:15:09]  INFO [lockfile] Scanning Language-specific Packages...
[May 18 21:15:09]  INFO [lockfile] Finding files under /home/vagrant/Downloads
2025-05-18T21:15:09Z	INFO	[npm] To collect the license information of packages, "npm install" needs to be performed beforehand	dir="home/vagrant/Downloads/node_modules"


Scan Summary
================
lockfile	ubuntu24.04	0 installed	250 libs





To view the detail, vuls tui is useful.
To send a report, run vuls report -h.
```

### setup
```console
PS C:\Users\vagrant> curl.exe -sL --create-dirs --output Downloads\package-lock.json https://raw.githubusercontent.com/vulsio/integration/refs/heads/main/data/lockfile/npm-v3/package-lock.json
```

### abspath
```powershell
PS C:\Users\vagrant> @"
version = "v2"

[default]

[servers]

[servers.lockfile]
host = "localhost"
port = "local"
scanMode           = ["fast"]
scanModules        = ["lockfile"]
lockfiles = ["C:\\Users\\vagrant\\Downloads\\package-lock.json"]
"@ | Set-Content config.toml

PS C:\Users\vagrant> .\vuls.exe scan
time="May 18 21:20:22" level=info msg="vuls-v0.32.0-build-20250519_061025_916f9da" 
time="May 18 21:20:22" level=info msg="Start scanning" 
time="May 18 21:20:22" level=info msg="config: C:\\Users\\vagrant\\config.toml"
time="May 18 21:20:22" level=info msg="Validating config..."
time="May 18 21:20:22" level=info msg="Detecting Server/Container OS... "
time="May 18 21:20:22" level=info msg="Detecting OS of servers... "
time="May 18 21:20:27" level=info msg="(1/1) Detected: lockfile: windows Windows Server 2022" 
time="May 18 21:20:27" level=info msg="Detecting OS of containers... " 
time="May 18 21:20:27" level=info msg="Checking Scan Modes... "
time="May 18 21:20:27" level=info msg="Detecting Platforms... "
time="May 18 21:20:40" level=info msg="(1/1) lockfile is running on other" 
time="May 18 21:20:40" level=info msg="Scanning Language-specific Packages..." 
2025-05-18T21:20:40Z    INFO    [npm] To collect the license information of packages, "npm install" needs to be performed beforehand    dir="C/Users/vagrant/Downloads/node_modules"


Scan Summary
================
lockfile        windowsWindows Server 2022      0 installed, 0 updatable        250 libs





To view the detail, vuls tui is useful.
To send a report, run vuls report -h.
```

### relpath
```powershell
PS C:\Users\vagrant> @"
version = "v2"

[default]

[servers]

[servers.lockfile]
host = "localhost"
port = "local"
scanMode           = ["fast"]
scanModules        = ["lockfile"]
lockfiles = ["Downloads\\package-lock.json"]
"@ | Set-Content config.toml

PS C:\Users\vagrant> .\vuls.exe scan
time="May 18 21:22:13" level=info msg="vuls-v0.32.0-build-20250519_061025_916f9da" 
time="May 18 21:22:13" level=info msg="Start scanning" 
time="May 18 21:22:13" level=info msg="config: C:\\Users\\vagrant\\config.toml"
time="May 18 21:22:13" level=info msg="Validating config..."
time="May 18 21:22:13" level=info msg="Detecting Server/Container OS... "
time="May 18 21:22:13" level=info msg="Detecting OS of servers... "
time="May 18 21:22:17" level=info msg="(1/1) Detected: lockfile: windows Windows Server 2022" 
time="May 18 21:22:17" level=info msg="Detecting OS of containers... " 
time="May 18 21:22:17" level=info msg="Checking Scan Modes... "
time="May 18 21:22:17" level=info msg="Detecting Platforms... "
time="May 18 21:22:29" level=info msg="(1/1) lockfile is running on other" 
time="May 18 21:22:29" level=info msg="Scanning Language-specific Packages..." 
2025-05-18T21:22:31Z    INFO    [npm] To collect the license information of packages, "npm install" needs to be performed beforehand    dir="C/Users/vagrant/Downloads/node_modules"


Scan Summary
================
lockfile        windowsWindows Server 2022      0 installed, 0 updatable        250 libs





To view the detail, vuls tui is useful.
To send a report, run vuls report -h.
```

### findlock
```powershell
PS C:\Users\vagrant> @"
version = "v2"

[default]

[servers]

[servers.lockfile]
host = "localhost"
port = "local"
scanMode           = ["fast"]
scanModules        = ["lockfile"]
findLock = true
findLockDirs = ["C:\\Users\\vagrant\\Downloads\\"]
"@ | Set-Content config.toml

PS C:\Users\vagrant> .\vuls.exe scan
time="May 18 21:20:59" level=info msg="vuls-v0.32.0-build-20250519_061025_916f9da" 
time="May 18 21:20:59" level=info msg="Start scanning" 
time="May 18 21:20:59" level=info msg="config: C:\\Users\\vagrant\\config.toml"
time="May 18 21:20:59" level=info msg="Validating config..."
time="May 18 21:20:59" level=info msg="Detecting Server/Container OS... "
time="May 18 21:20:59" level=info msg="Detecting OS of servers... "
time="May 18 21:21:04" level=info msg="(1/1) Detected: lockfile: windows Windows Server 2022" 
time="May 18 21:21:04" level=info msg="Detecting OS of containers... " 
time="May 18 21:21:04" level=info msg="Checking Scan Modes... "
time="May 18 21:21:04" level=info msg="Detecting Platforms... "
time="May 18 21:21:15" level=info msg="(1/1) lockfile is running on other" 
time="May 18 21:21:15" level=info msg="Scanning Language-specific Packages..." 
time="May 18 21:21:15" level=info msg="Finding files under \"C:\\Users\\vagrant\\Downloads\\\""
2025-05-18T21:21:17Z    INFO    [npm] To collect the license information of packages, "npm install" needs to be performed beforehand    dir="C/Users/vagrant/Downloads/node_modules"


Scan Summary
================
lockfile        windowsWindows Server 2022      0 installed, 0 updatable        250 libs





To view the detail, vuls tui is useful.
To send a report, run vuls report -h.
```

### setup
```console
$ curl -sL --create-dirs --output Downloads/package-lock.json https://raw.githubusercontent.com/vulsio/integration/refs/heads/main/data/lockfile/npm-v3/package-lock.json
```

### abspath
```console
$ cat << EOS > config.toml
version = "v2"

[default]

[servers]

[servers.lockfile]
host = "127.0.0.1"
port = "2222"
user = "vagrant"
keyPath = "/home/vuls/.ssh/id_rsa"
scanMode           = ["fast"]
scanModules        = ["lockfile"]
lockfiles = ["/home/vagrant/Downloads/package-lock.json"]
EOS

$ ./vuls scan
[May 19 06:16:25]  INFO [localhost] vuls-v0.32.0-build-20250519_061016_916f9da
[May 19 06:16:25]  INFO [localhost] Start scanning
[May 19 06:16:25]  INFO [localhost] config: /home/mainek00n/github/github.com/MaineK00n/vuls/config.toml
[May 19 06:16:25]  INFO [localhost] Validating config...
[May 19 06:16:25]  INFO [localhost] Detecting Server/Container OS... 
[May 19 06:16:25]  INFO [localhost] Detecting OS of servers... 
[May 19 06:16:25]  INFO [localhost] (1/1) Detected: lockfile: ubuntu 24.04
[May 19 06:16:25]  INFO [localhost] Detecting OS of containers... 
[May 19 06:16:25]  INFO [localhost] Checking Scan Modes... 
[May 19 06:16:25]  INFO [localhost] Detecting Platforms... 
[May 19 06:16:27]  INFO [localhost] (1/1) lockfile is running on other
[May 19 06:16:27]  INFO [lockfile] Scanning Language-specific Packages...
2025-05-19T06:16:27+09:00	INFO	[npm] To collect the license information of packages, "npm install" needs to be performed beforehand	dir="home/vagrant/Downloads/node_modules"


Scan Summary
================
lockfile	ubuntu24.04	0 installed	250 libs





To view the detail, vuls tui is useful.
To send a report, run vuls report -h.
```

### relpath
```console
$ cat << EOS > config.toml
version = "v2"

[default]

[servers]

[servers.lockfile]
host = "127.0.0.1"
port = "2222"
user = "vagrant"
keyPath = "/home/vuls/.ssh/id_rsa"
scanMode           = ["fast"]
scanModules        = ["lockfile"]
lockfiles = ["Downloads/package-lock.json"]
EOS

$ ./vuls scan
[May 19 06:16:46]  INFO [localhost] vuls-v0.32.0-build-20250519_061016_916f9da
[May 19 06:16:46]  INFO [localhost] Start scanning
[May 19 06:16:46]  INFO [localhost] config: /home/mainek00n/github/github.com/MaineK00n/vuls/config.toml
[May 19 06:16:46]  INFO [localhost] Validating config...
[May 19 06:16:46]  INFO [localhost] Detecting Server/Container OS... 
[May 19 06:16:46]  INFO [localhost] Detecting OS of servers... 
[May 19 06:16:46]  INFO [localhost] (1/1) Detected: lockfile: ubuntu 24.04
[May 19 06:16:46]  INFO [localhost] Detecting OS of containers... 
[May 19 06:16:46]  INFO [localhost] Checking Scan Modes... 
[May 19 06:16:46]  INFO [localhost] Detecting Platforms... 
[May 19 06:16:48]  INFO [localhost] (1/1) lockfile is running on other
[May 19 06:16:48]  INFO [lockfile] Scanning Language-specific Packages...
2025-05-19T06:16:48+09:00	INFO	[npm] To collect the license information of packages, "npm install" needs to be performed beforehand	dir="home/vagrant/Downloads/node_modules"


Scan Summary
================
lockfile	ubuntu24.04	0 installed	250 libs





To view the detail, vuls tui is useful.
To send a report, run vuls report -h.
```

### findlock
```console
$ cat << EOS > config.toml
version = "v2"

[default]

[servers]

[servers.lockfile]
host = "127.0.0.1"
port = "2222"
user = "vagrant"
keyPath = "/home/vuls/.ssh/id_rsa"
scanMode           = ["fast"]
scanModules        = ["lockfile"]
findLock = true
findLockDirs = ["/home/vagrant/Downloads"]
EOS

$ ./vuls scan
[May 19 06:17:18]  INFO [localhost] vuls-v0.32.0-build-20250519_061016_916f9da
[May 19 06:17:18]  INFO [localhost] Start scanning
[May 19 06:17:18]  INFO [localhost] config: /home/mainek00n/github/github.com/MaineK00n/vuls/config.toml
[May 19 06:17:18]  INFO [localhost] Validating config...
[May 19 06:17:18]  INFO [localhost] Detecting Server/Container OS... 
[May 19 06:17:18]  INFO [localhost] Detecting OS of servers... 
[May 19 06:17:18]  INFO [localhost] (1/1) Detected: lockfile: ubuntu 24.04
[May 19 06:17:18]  INFO [localhost] Detecting OS of containers... 
[May 19 06:17:18]  INFO [localhost] Checking Scan Modes... 
[May 19 06:17:18]  INFO [localhost] Detecting Platforms... 
[May 19 06:17:20]  INFO [localhost] (1/1) lockfile is running on other
[May 19 06:17:20]  INFO [lockfile] Scanning Language-specific Packages...
[May 19 06:17:20]  INFO [lockfile] Finding files under /home/vagrant/Downloads
2025-05-19T06:17:21+09:00	INFO	[npm] To collect the license information of packages, "npm install" needs to be performed beforehand	dir="home/vagrant/Downloads/node_modules"


Scan Summary
================
lockfile	ubuntu24.04	0 installed	250 libs





To view the detail, vuls tui is useful.
To send a report, run vuls report -h.
```

### setup
```console
PS C:\Users\vagrant> curl.exe -sL --create-dirs --output Downloads\package-lock.json https://raw.githubusercontent.com/vulsio/integration/refs/heads/main/data/lockfile/npm-v3/package-lock.json
```

### abspath
```console
$ cat << EOS > config.toml
version = "v2"

[default]

[servers]

[servers.lockfile]
host = "127.0.0.1"
port = "2222"
user = "vagrant"
keyPath = "/home/vuls/.ssh/id_rsa"
scanMode           = ["fast"]
scanModules        = ["lockfile"]
lockfiles = ["C:\\Users\\vagrant\\Downloads\\package-lock.json"]
EOS

$ ./vuls scan
[May 19 06:23:03]  INFO [localhost] vuls-v0.32.0-build-20250519_061016_916f9da
[May 19 06:23:03]  INFO [localhost] Start scanning
[May 19 06:23:03]  INFO [localhost] config: /home/mainek00n/github/github.com/MaineK00n/vuls/config.toml
[May 19 06:23:03]  INFO [localhost] Validating config...
[May 19 06:23:03]  INFO [localhost] Detecting Server/Container OS... 
[May 19 06:23:03]  INFO [localhost] Detecting OS of servers... 
[May 19 06:23:07]  INFO [localhost] (1/1) Detected: lockfile: windows Windows Server 2022
[May 19 06:23:07]  INFO [localhost] Detecting OS of containers... 
[May 19 06:23:07]  INFO [localhost] Checking Scan Modes... 
[May 19 06:23:07]  INFO [localhost] Detecting Platforms... 
[May 19 06:23:14]  INFO [localhost] (1/1) lockfile is running on other
[May 19 06:23:14]  INFO [lockfile] Scanning Language-specific Packages...
2025-05-19T06:23:17+09:00	INFO	[npm] To collect the license information of packages, "npm install" needs to be performed beforehand	dir="C/Users/vagrant/Downloads/node_modules"


Scan Summary
================
lockfile	windowsWindows Server 2022	0 installed, 0 updatable	250 libs





To view the detail, vuls tui is useful.
To send a report, run vuls report -h.
```

### relpath
```console
$ cat << EOS > config.toml
version = "v2"

[default]

[servers]

[servers.lockfile]
host = "127.0.0.1"
port = "2222"
user = "vagrant"
keyPath = "/home/vuls/.ssh/id_rsa"
scanMode           = ["fast"]
scanModules        = ["lockfile"]
lockfiles = ["Downloads\\package-lock.json"]
EOS

$ ./vuls scan
[May 19 06:23:34]  INFO [localhost] vuls-v0.32.0-build-20250519_061016_916f9da
[May 19 06:23:34]  INFO [localhost] Start scanning
[May 19 06:23:34]  INFO [localhost] config: /home/mainek00n/github/github.com/MaineK00n/vuls/config.toml
[May 19 06:23:34]  INFO [localhost] Validating config...
[May 19 06:23:34]  INFO [localhost] Detecting Server/Container OS... 
[May 19 06:23:34]  INFO [localhost] Detecting OS of servers... 
[May 19 06:23:37]  INFO [localhost] (1/1) Detected: lockfile: windows Windows Server 2022
[May 19 06:23:37]  INFO [localhost] Detecting OS of containers... 
[May 19 06:23:37]  INFO [localhost] Checking Scan Modes... 
[May 19 06:23:37]  INFO [localhost] Detecting Platforms... 
[May 19 06:23:44]  INFO [localhost] (1/1) lockfile is running on other
[May 19 06:23:44]  INFO [lockfile] Scanning Language-specific Packages...
2025-05-19T06:23:49+09:00	INFO	[npm] To collect the license information of packages, "npm install" needs to be performed beforehand	dir="C/Users/vagrant/Downloads/node_modules"


Scan Summary
================
lockfile	windowsWindows Server 2022	0 installed, 0 updatable	250 libs





To view the detail, vuls tui is useful.
To send a report, run vuls report -h.
```

### findlock
```console
$ cat << EOS > config.toml
version = "v2"

[default]

[servers]

[servers.lockfile]
host = "127.0.0.1"
port = "2222"
user = "vagrant"
keyPath = "/home/vuls/.ssh/id_rsa"
scanMode           = ["fast"]
scanModules        = ["lockfile"]
findLock = true
findLockDirs = ["C:\\Users\\vagrant\\Downloads"]
EOS

$ ./vuls scan
[May 19 06:24:34]  INFO [localhost] vuls-v0.32.0-build-20250519_061016_916f9da
[May 19 06:24:34]  INFO [localhost] Start scanning
[May 19 06:24:34]  INFO [localhost] config: /home/mainek00n/github/github.com/MaineK00n/vuls/config.toml
[May 19 06:24:34]  INFO [localhost] Validating config...
[May 19 06:24:34]  INFO [localhost] Detecting Server/Container OS... 
[May 19 06:24:34]  INFO [localhost] Detecting OS of servers... 
[May 19 06:24:37]  INFO [localhost] (1/1) Detected: lockfile: windows Windows Server 2022
[May 19 06:24:37]  INFO [localhost] Detecting OS of containers... 
[May 19 06:24:37]  INFO [localhost] Checking Scan Modes... 
[May 19 06:24:37]  INFO [localhost] Detecting Platforms... 
[May 19 06:24:43]  INFO [localhost] (1/1) lockfile is running on other
[May 19 06:24:43]  INFO [lockfile] Scanning Language-specific Packages...
[May 19 06:24:43]  INFO [lockfile] Finding files under \"C:\Users\vagrant\Downloads\"
2025-05-19T06:24:48+09:00	INFO	[npm] To collect the license information of packages, "npm install" needs to be performed beforehand	dir="C/Users/vagrant/Downloads/node_modules"


Scan Summary
================
lockfile	windowsWindows Server 2022	0 installed, 0 updatable	250 libs





To view the detail, vuls tui is useful.
To send a report, run vuls report -h.
```

## remote scan (windows to linux)
I don't have an environment where I can reproduce this.

### setup
```console
PS C:\Users\vagrant> curl.exe -sL --create-dirs --output Downloads\package-lock.json https://raw.githubusercontent.com/vulsio/integration/refs/heads/main/data/lockfile/npm-v3/package-lock.json
```

### abspath
```powershell
PS C:\Users\vagrant> @"
version = "v2"

[default]

[servers]

[servers.lockfile]
host = "127.0.0.1"
port = "22"
user = "vagrant"
keyPath = "C:\\Users\\vagrant\\.ssh\\id_rsa"
scanMode           = ["fast"]
scanModules        = ["lockfile"]
lockfiles = ["C:\\Users\\vagrant\\Downloads\\package-lock.json"]
"@ | Set-Content config.toml

PS C:\Users\vagrant> .\vuls.exe scan
time="May 18 21:29:46" level=info msg="vuls-v0.32.0-build-20250519_061025_916f9da" 
time="May 18 21:29:46" level=info msg="Start scanning" 
time="May 18 21:29:46" level=info msg="config: C:\\Users\\vagrant\\config.toml" 
time="May 18 21:29:46" level=info msg="Validating config..." 
time="May 18 21:29:46" level=info msg="Detecting Server/Container OS... " 
time="May 18 21:29:46" level=info msg="Detecting OS of servers... " 
time="May 18 21:29:52" level=info msg="(1/1) Detected: lockfile: windows Windows Server 2022" 
time="May 18 21:29:52" level=info msg="Detecting OS of containers... " 
time="May 18 21:29:52" level=info msg="Checking Scan Modes... " 
time="May 18 21:29:52" level=info msg="Detecting Platforms... " 
time="May 18 21:30:01" level=info msg="(1/1) lockfile is running on other" 
time="May 18 21:30:01" level=info msg="Scanning Language-specific Packages..." 
2025-05-18T21:30:04Z    INFO    [npm] To collect the license information of packages, "npm install" needs to be performed beforehand    dir="C/Users/vagrant/Downloads/node_modules"


Scan Summary
================
lockfile        windowsWindows Server 2022      0 installed, 0 updatable        250 libs





To view the detail, vuls tui is useful.
To send a report, run vuls report -h.
```

### relpath
```powershell
PS C:\Users\vagrant> @"
version = "v2"

[default]

[servers]

[servers.lockfile]
host = "127.0.0.1"
port = "22"
user = "vagrant"
keyPath = "C:\\Users\\vagrant\\.ssh\\id_rsa"
scanMode           = ["fast"]
scanModules        = ["lockfile"]
lockfiles = ["Downloads\\package-lock.json"]
"@ | Set-Content config.toml

PS C:\Users\vagrant> .\vuls.exe scan
time="May 18 21:31:48" level=info msg="vuls-v0.32.0-build-20250519_061025_916f9da" 
time="May 18 21:31:48" level=info msg="Start scanning" 
time="May 18 21:31:48" level=info msg="config: C:\\Users\\vagrant\\config.toml" 
time="May 18 21:31:48" level=info msg="Validating config..." 
time="May 18 21:31:48" level=info msg="Detecting Server/Container OS... " 
time="May 18 21:31:48" level=info msg="Detecting OS of servers... " 
time="May 18 21:31:55" level=info msg="(1/1) Detected: lockfile: windows Windows Server 2022" 
time="May 18 21:31:55" level=info msg="Detecting OS of containers... " 
time="May 18 21:31:55" level=info msg="Checking Scan Modes... " 
time="May 18 21:31:55" level=info msg="Detecting Platforms... " 
time="May 18 21:32:04" level=info msg="(1/1) lockfile is running on other" 
time="May 18 21:32:04" level=info msg="Scanning Language-specific Packages..." 
2025-05-18T21:32:10Z    INFO    [npm] To collect the license information of packages, "npm install" needs to be performed beforehand    dir="C/Users/vagrant/Downloads/node_modules"


Scan Summary
================
lockfile        windowsWindows Server 2022      0 installed, 0 updatable        250 libs





To view the detail, vuls tui is useful.
To send a report, run vuls report -h.
```

### findlock
```powershell
PS C:\Users\vagrant> @"
version = "v2"

[default]

[servers]

[servers.lockfile]
host = "127.0.0.1"
port = "22"
user = "vagrant"
keyPath = "C:\\Users\\vagrant\\.ssh\\id_rsa"
scanMode           = ["fast"]
scanModules        = ["lockfile"]
findLock = true
findLockDirs = ["C:\\Users\\vagrant\\Downloads"]
"@ | Set-Content config.toml

PS C:\Users\vagrant> .\vuls.exe scan
time="May 18 21:32:26" level=info msg="vuls-v0.32.0-build-20250519_061025_916f9da" 
time="May 18 21:32:26" level=info msg="Start scanning" 
time="May 18 21:32:26" level=info msg="config: C:\\Users\\vagrant\\config.toml"
time="May 18 21:32:26" level=info msg="Validating config..."
time="May 18 21:32:26" level=info msg="Detecting Server/Container OS... "
time="May 18 21:32:26" level=info msg="Detecting OS of servers... "
time="May 18 21:32:35" level=info msg="(1/1) Detected: lockfile: windows Windows Server 2022" 
time="May 18 21:32:35" level=info msg="Detecting OS of containers... " 
time="May 18 21:32:35" level=info msg="Checking Scan Modes... "
time="May 18 21:32:35" level=info msg="Detecting Platforms... "
time="May 18 21:32:43" level=info msg="(1/1) lockfile is running on other" 
time="May 18 21:32:43" level=info msg="Scanning Language-specific Packages..." 
time="May 18 21:32:43" level=info msg="Finding files under \\\"C:\\Users\\vagrant\\Downloads\\\""
2025-05-18T21:32:50Z    INFO    [npm] To collect the license information of packages, "npm install" needs to be performed beforehand    dir="C/Users/vagrant/Downloads/node_modules"


Scan Summary
================
lockfile        windowsWindows Server 2022      0 installed, 0 updatable        250 libs





To view the detail, vuls tui is useful.
To send a report, run vuls report -h.
```

# Checklist:
You don't have to satisfy all of the following.

- [ ] Write tests
- [ ] Write documentation
- [x] Check that there aren't other open pull requests for the same issue/feature
- [x] Format your source code by `make fmt`
- [x] Pass the test by `make test`
- [x] Provide verification config / commands
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES

# Reference

### CODE REVIEW

File: scanner/windows.go [hunk 1]
```diff
@@ -4890,3 +4893,186 @@ func (w *windows) detectRunningOnAws() (bool, string, error) {
...
+	}
+
+	// auto detect lockfile
+	if w.ServerInfo.FindLock {
+		cmd := func() string {
+			switch w.shell {
+			case "powershell":
+				dir := func() string {
+					if len(w.ServerInfo.FindLockDirs) == 0 {
+						w.log.Infof("It's recommended to specify FindLockDirs in config.toml. If FindLockDirs is not specified, all directories under / will be searched, which may increase CPU load")
```
Comment (shino) [inline scanner/windows.go:4925]:
```suggestion
						w.log.Infof("It's recommended to specify FindLockDirs in config.toml. If FindLockDirs is not specified, all directories under C:\\ will be searched, which may increase CPU load")
```

Comment (MaineK00n) [reply scanner/windows.go]: fixed: https://github.com/future-architect/vuls/compare/8cb1c4a6b8f99cd48af8eca995961a4425467f42..cc3b32c3f7f68964623f332022ae4e6d92dab8fc#diff-50bc16bd65521a5b32a24e0a74f34aabfe3cc84f3d98fbc0fe47d4ddc330085a

**Review by shino — APPROVED** [review]
🥂
