### PR TITLE
fix(scanner/lockfile): fix binary lockfile scan on windows

### LINKED ISSUE #2305: binary lockfile analysis broken on windows
# What did you do? (required. The issue will be **closed** when not provided.)

On Windows, in version v0.33.2,  scans were able to analyze binary files such as JARs, but starting from v0.33.3, this no longer works.
It seems that pseudo scans are not affected.
This issue is likely caused by the following commit.
https://github.com/future-architect/vuls/commit/48e5d68ceda1ef0295511b9b6db1504b9830be74

# Steps to reproduce the behaviour
## setup
```console
PS C:\Users\vagrant> curl.exe -sL --create-dirs --output Downloads\log4j-core-2.13.0.jar https://github.com/vulsio/integration/raw/refs/heads/main/data/lockfile/log4j-core-2.13.0.jar
```

## pseudo scan(v0.33.4)
```console
PS C:\Users\vagrant> cmd.exe /c 'curl.exe -sL https://github.com/future-architect/vuls/releases/download/v0.33.4/vuls_0.33.4_windows_amd64.tar.gz | tar.exe zxf - vuls.exe'

PS C:\Users\vagrant> @"
version = "v2"

[default]

[servers]

[servers.lockfile]
type = "pseudo"
scanMode           = ["fast"]
scanModules        = ["lockfile"]
lockfiles = ["C:\\Users\\vagrant\\Downloads\\log4j-core-2.13.0.jar"]
"@ | Set-Content config.toml

PS C:\Users\vagrant> .\vuls.exe scan
time="Sep  4 02:26:33" level=info msg="vuls-0.33.4-0993588f1129ea7013049e282122798e38ff1b4b-2025-08-27T05:24:54Z" 
...
Scan Summary
================
lockfile        pseudo  0 installed, 0 updatable        1 libs
```

## local scan(v0.33.2)
```console
PS C:\Users\vagrant> cmd.exe /c 'curl.exe -sL https://github.com/future-architect/vuls/releases/download/v0.33.2/vuls_0.33.2_windows_amd64.tar.gz | tar.exe zxf - vuls.exe'

PS C:\Users\vagrant> @"
version = "v2"

[default]

[servers]

[servers.lockfile]
host = "localhost"
port = "local"
scanMode           = ["fast"]
scanModules        = ["lockfile"]
lockfiles = ["C:\\Users\\vagrant\\Downloads\\log4j-core-2.13.0.jar"]
"@ | Set-Content config.toml

PS C:\Users\vagrant> .\vuls.exe scan
time="Sep  4 02:30:59" level=info msg="vuls-0.33.2-d79cf40de3422117f8ff428d53665abdb08f7afc-2025-07-02T04:55:24Z" 
...
Scan Summary
================
lockfile        windowsWindows 11 Version 24H2 for x64-based Systems    0 installed, 0 updatable        1 libs
```

## local scan(v0.33.3)
```console
PS C:\Users\vagrant> cmd.exe /c 'curl.exe -sL https://github.com/future-architect/vuls/releases/download/v0.33.3/vuls_0.33.3_windows_amd64.tar.gz | tar.exe zxf - vuls.exe'

PS C:\Users\vagrant> @"
version = "v2"

[default]

[servers]

[servers.lockfile]
host = "localhost"
port = "local"
scanMode           = ["fast"]
scanModules        = ["lockfile"]
lockfiles = ["C:\\Users\\vagrant\\Downloads\\log4j-core-2.13.0.jar"]
"@ | Set-Content config.toml

PS C:\Users\vagrant> .\vuls.exe scan
time="Sep  4 02:36:05" level=info msg="vuls-0.33.3-30a8e70f58bba07a9fd82ef38c18a6f1a3791f51-2025-08-20T10:22:09Z" 
...
Scan Summary
================
lockfile        windowsWindows 11 Version 24H2 for x64-based Systems    0 installed, 0 updatable
```

## local scan(v0.33.4)
```console
PS C:\Users\vagrant> cmd.exe /c 'curl.exe -sL https://github.com/future-architect/vuls/releases/download/v0.33.4/vuls_0.33.4_windows_amd64.tar.gz | tar.exe zxf - vuls.exe'

PS C:\Users\vagrant> @"
version = "v2"

[default]

[servers]

[servers.lockfile]
host = "localhost"
port = "local"
scanMode           = ["fast"]
scanModules        = ["lockfile"]
lockfiles = ["C:\\Users\\vagrant\\Downloads\\log4j-core-2.13.0.jar"]
"@ | Set-Content config.toml

PS C:\Users\vagrant> .\vuls.exe scan
time="Sep  4 02:27:44" level=info msg="vuls-0.33.4-0993588f1129ea7013049e282122798e38ff1b4b-2025-08-27T05:24:54Z" 
...
Scan Summary
================
lockfile        windowsWindows 11 Version 24H2 for x64-based Systems    0 installed, 0 updatable
```

### PR DESCRIPTION
**Pull request by MaineK00n**
If this Pull Request is work in progress, Add a prefix of “[WIP]” in the title.

# What did you implement:

Fixes #2305 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
## setup
```powershell
PS C:\Users\vagrant> curl.exe -sL --create-dirs --output Downloads\log4j-core-2.13.0.jar https://github.com/vulsio/integration/raw/refs/heads/main/data/lockfile/log4j-core-2.13.0.jar
PS C:\Users\vagrant> curl.exe -sL --create-dirs --output Downloads/package-lock.json https://raw.githubusercontent.com/vulsio/integration/refs/heads/main/data/lockfile/npm-v3/package-lock.json
```

### local scan
```powershell
PS C:\Users\vagrant> @"
version = "v2"

[default]

[servers]

[servers.lockfile]
host = "localhost"
port = "local"
scanMode           = ["fast"]
scanModules        = ["lockfile"]
lockfiles = [
    "C:\\Users\\vagrant\\Downloads\\package-lock.json",
    "C:\\Users\\vagrant\\Downloads\\log4j-core-2.13.0.jar"
]
"@ | Set-Content config.toml

PS C:\Users\vagrant> cmd.exe /c 'curl.exe -sL https://github.com/future-architect/vuls/releases/download/v0.33.4/vuls_0.33.4_windows_amd64.tar.gz | tar.exe zxf - vuls.exe'
PS C:\Users\vagrant> .\vuls.exe scan
time="Sep  4 07:28:21" level=info msg="vuls-0.33.4-0993588f1129ea7013049e282122798e38ff1b4b-2025-08-27T05:24:54Z" 
...
Scan Summary
================
lockfile        windowsWindows 11 Version 24H2 for x64-based Systems    0 installed, 0 updatable        250 libs

PS C:\Users\vagrant> cat .\results\2025-09-04T07-28-49-0700\lockfile.json | Select-String -SimpleMatch '"path": "C:\\Users\\vagrant\\Downloads\\' 

            "path": "C:\\Users\\vagrant\\Downloads\\package-lock.json"
```

### remote scan (linux -> windows:CMD)
```bash
$ cat << EOS > config.toml
version = "v2"

[default]

[servers]

[servers.lockfile]
host = "127.0.0.1"
port = "2222"
user = "vagrant"
keyPath = "/home/vuls/.ssh/id_rsa"
scanMode           = ["fast"]
scanModules        = ["lockfile"]
lockfiles = [
    "C:\\Users\\vagrant\\Downloads\\package-lock.json",
    "C:\\Users\\vagrant\\Downloads\\log4j-core-2.13.0.jar"
]
EOS

$ curl -sL https://github.com/future-architect/vuls/releases/download/v0.33.4/vuls_0.33.4_linux_amd64.tar.gz | tar zxf - vuls
$ ./vuls scan
[Sep  4 23:31:26]  INFO [localhost] vuls-0.33.4-0993588f1129ea7013049e282122798e38ff1b4b-2025-08-27T05:24:54Z
...
Scan Summary
================
lockfile	windowsWindows 11 Version 24H2 for x64-based Systems	0 installed, 0 updatable	250 libs

$ jq -r '.libraries[].path' results/2025-09-04T23-31-42+0900/lockfile.json
C:\Users\vagrant\Downloads\package-lock.json
```

### local scan (CMD)
```console
vagrant@DESKTOP C:\Users\vagrant> echo version = "v2" > config.toml
vagrant@DESKTOP C:\Users\vagrant> echo. >> config.toml
vagrant@DESKTOP C:\Users\vagrant> echo [default] >> config.toml
vagrant@DESKTOP C:\Users\vagrant> echo. >> config.toml
vagrant@DESKTOP C:\Users\vagrant> echo [servers] >> config.toml
vagrant@DESKTOP C:\Users\vagrant> echo. >> config.toml
vagrant@DESKTOP C:\Users\vagrant> echo [servers.lockfile] >> config.toml
vagrant@DESKTOP C:\Users\vagrant> echo host = "localhost" >> config.toml
vagrant@DESKTOP C:\Users\vagrant> echo port = "local" >> config.toml
vagrant@DESKTOP C:\Users\vagrant> echo scanMode           = ["fast"] >> config.toml
vagrant@DESKTOP C:\Users\vagrant> echo scanModules        = ["lockfile"] >> config.toml
vagrant@DESKTOP C:\Users\vagrant> echo lockfiles = [ >> config.toml
vagrant@DESKTOP C:\Users\vagrant> echo     "C:\Users\vagrant\Downloads\package-lock.json", >> config.toml
vagrant@DESKTOP C:\Users\vagrant> echo     "C:\Users\vagrant\Downloads\log4j-core-2.13.0.jar" >> config.toml
vagrant@DESKTOP C:\Users\vagrant> echo ] >> config.toml

vagrant@DESKTOP C:\Users\vagrant> .\vuls.exe scan
...
Scan Summary
================
lockfile        windowsWindows 11 Version 24H2 for x64-based Systems    0 installed, 0 updatable        251 libs

vagrant@DESKTOP C:\Users\vagrant> findstr "\"path\": \"C:\\Users\\vagrant\\Downloads\\" .\results\2025-09-04T07-39-30-0700\lockfile.json
            "path": "C:\\Users\\vagrant\\Downloads\\package-lock.json"
            "path": "C:\\Users\\vagrant\\Downloads\\log4j-core-2.13.0.jar"
```

### local scan (powershell)
```powershell
PS C:\Users\vagrant> @"
version = "v2"

[default]

[servers]

[servers.lockfile]
host = "localhost"
port = "local"
scanMode           = ["fast"]
scanModules        = ["lockfile"]
lockfiles = [
    "C:\\Users\\vagrant\\Downloads\\package-lock.json",
    "C:\\Users\\vagrant\\Downloads\\log4j-core-2.13.0.jar"
]
"@ | Set-Content config.toml

PS C:\Users\vagrant> .\vuls.exe scan
...
Scan Summary
================
lockfile        windowsWindows 11 Version 24H2 for x64-based Systems    0 installed, 0 updatable        251 libs      

PS C:\Users\vagrant> cat .\results\2025-09-04T07-46-16-0700\lockfile.json | Select-String -SimpleMatch '"path": "C:\\Users\\vagrant\\Downloads\\'

            "path": "C:\\Users\\vagrant\\Downloads\\package-lock.json"
            "path": "C:\\Users\\vagrant\\Downloads\\log4j-core-2.13.0.jar"
```

### remote scan (linux -> windows:CMD)
```bash
$ cat << EOS > config.toml
version = "v2"

[default]

[servers]

[servers.lockfile]
host = "127.0.0.1"
port = "2222"
user = "vagrant"
keyPath = "/home/vuls/.ssh/id_rsa"
scanMode           = ["fast"]
scanModules        = ["lockfile"]
lockfiles = [
    "C:\\Users\\vagrant\\Downloads\\package-lock.json",
    "C:\\Users\\vagrant\\Downloads\\log4j-core-2.13.0.jar"
]
EOS

$ ./vuls scan
...
Scan Summary
================
lockfile        windowsWindows 11 Version 24H2 for x64-based Systems    0 installed, 0 updatable        251 libs 

$ jq -r '.libraries[].path' results/2025-09-04T23-51-31+0900/lockfile.json 
C:\Users\vagrant\Downloads\package-lock.json
C:\Users\vagrant\Downloads\log4j-core-2.13.0.jar
```

# Checklist:
You don't have to satisfy all of the following.

- [ ] Write tests
- [ ] Write documentation
- [x] Check that there aren't other open pull requests for the same issue/feature
- [x] Format your source code by `make fmt`
- [x] Pass the test by `make test`
- [x] Provide verification config / commands
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES

# Reference

### CODE REVIEW

File: scanner/windows.go [hunk 1]
```diff
@@ -5044,11 +5053,51 @@
...
+			contents, err := func() ([]byte, error) {
+				var bs []byte
+
+				scanner := bufio.NewScanner(strings.NewReader(r.Stdout))
+				for scanner.Scan() {
+					b, err := strconv.Atoi(scanner.Text())
+					if err != nil {
+						return nil, xerrors.Errorf("Failed to convert %q to type int", scanner.Text())
+					}
+					bs = append(bs, byte(b))
```
[the remark this answers is not in the document]
Comment (MaineK00n) [reply scanner/windows.go]: applied

File: scanner/windows.go [hunk 2]
```diff
@@ -5044,11 +5053,51 @@ func (w *windows) scanLibraries() (err error) {
...
+
+					v2, err := version.NewVersion("6.0")
+					if err != nil {
+						return fmt.Sprintf("[System.IO.File]::ReadAllBytes(\"%s\")", abspath)
+					}
+
+					if v1.LessThan(v2) {
+						return fmt.Sprintf("Get-Content -Path %s -Encoding Byte -Raw", abspath)
+					}
+					return fmt.Sprintf("Get-Content -Path %s -AsByteStream", abspath)
```
Comment (shino) [inline scanner/windows.go]:
```suggestion
						return fmt.Sprintf("Get-Content -Path \"%s\" -Encoding Byte -Raw", abspath)
					}
					return fmt.Sprintf("Get-Content -Path \"%s\" -AsByteStream", abspath)
```

Comment (shino) [reply scanner/windows.go]: Because there are no quotes in L5046 of original (before) one, so this quoting may be needless worry... Worth to add them?

Comment (MaineK00n) [reply scanner/windows.go]: Looking at the documentation from Microsoft, it seems that quotes are not necessary.
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-content?view=powershell-5.1#example-8-get-file-contents-as-a-byte-array
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-content?view=powershell-7.5#example-8-get-file-contents-as-a-byte-array

Comment (MaineK00n) [reply scanner/windows.go]: If the path contains spaces, it must be quoted.
```powershell
PS C:\Users\vagrant> Get-Content -Path test .txt
Get-Content : A positional parameter cannot be found that accepts argument '.txt'.
At line:1 char:1
+ Get-Content -Path test .txt
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-Content], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.GetContentCommand
 
PS C:\Users\vagrant> Get-Content -Path 'test .txt'
PS C:\Users\vagrant>
```

Comment (MaineK00n) [reply scanner/windows.go]: quoted: https://github.com/future-architect/vuls/compare/b8f3c62980a111e62b15e6c60d41a342b064522e..64308a7459cf231d667def015ccd5c06e3a566fc

**Review by shino — APPROVED** [review]
🥂 🎊
