### PR TITLE
fix(scanner/windows): support when default shell is powershell

### LINKED ISSUE #1835: Remote scan from Linux to Windows fails
# What did you do? (required. The issue will be **closed** when not provided.)
When trying to do a remote scan from Linux to Windows, the scanner does not recognize Windows and the scan fails.
Successful SSH connection has been confirmed

config.toml
```
# See README for details: https://vuls.io/docs/en/usage-settings.html

version = "v2"

[saas]
  GroupID = xxxx
  Token = "xxxx"
  URL = "https://auth.vuls.biz/one-time-auth"

[default]

[servers]

  [servers.windowsserver]
    user = "Administrator"
    host = "192.168.0.124"
    port = "22"
    keyPath = "test"
    [servers.windowsserver.windows]
    serverSelection = 2
```

# What did you expect to happen?
Successful remote scan

# What happened instead?

* Current Output
```
vuls-saas@ip-192-168-0-136 vuls-saas]$ ./vuls scan --debug
[Jan 24 10:00:15]  INFO [localhost] vuls-v0.24.8-build-bbf53c7
[Jan 24 10:00:15]  INFO [localhost] Start scanning
[Jan 24 10:00:15]  INFO [localhost] config: /opt/vuls-saas/config.toml
[Jan 24 10:00:15] DEBUG [localhost] map[string]config.ServerInfo{
  "windowsserver": config.ServerInfo{
    BaseName:           "windowsserver",
    ServerName:         "windowsserver",
    User:               "Administrator",
    Host:               "192.168.0.124",
    IgnoreIPAddresses:  []string{},
    JumpServer:         []string{},
    Port:               "22",
    SSHConfigPath:      "",
    KeyPath:            "test",
    CpeNames:           []string{},
    ScanMode:           []string{},
    ScanModules:        []string{},
    OwaspDCXMLPath:     "",
    ContainersOnly:     false,
    ContainersIncluded: []string{},
    ContainersExcluded: []string{},
    ContainerType:      "",
    Containers:         map[string]config.ContainerSetting{},
    IgnoreCves:         []string{},
    IgnorePkgsRegexp:   []string{},
    GitHubRepos:        map[string]config.GitHubConf{},
    UUIDs:              map[string]string{},
    Memo:               "",
    Enablerepo:         []string{},
    Optional:           map[string]interface {}{},
    Lockfiles:          []string{},
    FindLock:           false,
    FindLockDirs:       []string{},
    Type:               "",
    IgnoredJSONKeys:    []string{},
    WordPress:          &config.WordPressConf{
      OSUser:  "",
      DocRoot: "",
      CmdPath: "",
      NoSudo:  false,
    },
    PortScan: &config.PortScanConf{
      IsUseExternalScanner: false,
      ScannerBinPath:       "",
      HasPrivileged:        false,
      ScanTechniques:       []string{},
      SourcePort:           "",
    },
    Windows: &config.WindowsConf{
      ServerSelection: 2,
      CabPath:         "",
    },
    IPv4Addrs:       []string{},
    IPv6Addrs:       []string{},
    IPSIdentifiers:  map[string]string{},
    LogMsgAnsiColor: "",
    Container:       config.Container{
      ContainerID: "",
      Name:        "",
      Image:       "",
    },
    Distro: config.Distro{
      Family:  "",
      Release: "",
    },
    Mode: config.ScanMode{
      flag: 0x01,
    },
    Module: config.ScanModule{
      flag: 0x0f,
    },
  },
}
[Jan 24 10:00:15]  INFO [localhost] Validating config...
[Jan 24 10:00:15]  INFO [localhost] Detecting Server/Container OS...
[Jan 24 10:00:15]  INFO [localhost] Detecting OS of servers...
[Jan 24 10:00:15] DEBUG [localhost] Validating SSH Settings for Server:windowsserver ...
[Jan 24 10:00:15] DEBUG [localhost] Executing... /usr/bin/ssh -G -i test -p 22 -l Administrator 192.168.0.124
[Jan 24 10:00:15] DEBUG [localhost] Setting SSH User:Administrator for Server:windowsserver ...
[Jan 24 10:00:15] DEBUG [localhost] Setting SSH Port:22 for Server:windowsserver ...
[Jan 24 10:00:15] DEBUG [localhost] Checking if the host's public key is in known_hosts...
[Jan 24 10:00:15] DEBUG [localhost] Executing... /usr/bin/ssh-keygen -F 192.168.0.124 -f /home/vuls-saas/.ssh/known_hosts
[Jan 24 10:00:15] DEBUG [localhost] Executing... exit
[Jan 24 10:00:16] DEBUG [localhost] execResult: servername: windowsserver
  cmd: /usr/bin/ssh -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=auto -o ControlPath=/home/vuls-saas/.vuls/cm-eacc137d-%C -o Controlpersist=10m -l Administrator -p 22 -i test -o PasswordAuthentication=no 192.168.0.124
  exitstatus: 0
  stdout:
  stderr: stty : The term 'stty' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:1
+ stty cols 1000; exit
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (stty:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


  err: %!s(<nil>)
[Jan 24 10:00:16] DEBUG [localhost] Executing... Get-ComputerInfo -Property WindowsProductName, OsVersion, WindowsEditionId, OsCSDVersion, CsSystemType, WindowsInstallationType
[Jan 24 10:00:17] DEBUG [localhost] execResult: servername: windowsserver
  cmd: /usr/bin/ssh -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=auto -o ControlPath=/home/vuls-saas/.vuls/cm-eacc137d-%C -o Controlpersist=10m -l Administrator -p 22 -i test -o PasswordAuthentication=no 192.168.0.124
  exitstatus: 1
  stdout:
  stderr: The string is missing the terminator: ".
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString


  err: %!s(<nil>)
[Jan 24 10:00:17] DEBUG [localhost] Executing... $WmiOS = (Get-WmiObject Win32_OperatingSystem); Format-List -InputObject $WmiOS -Property Caption, Version, OperatingSystemSKU, CSDVersion; $WmiCS = (Get-WmiObject Win32_ComputerSystem); Format-List -InputObject $WmiCS -Property SystemType, DomainRole
[Jan 24 10:00:17] DEBUG [localhost] execResult: servername: windowsserver
  cmd: /usr/bin/ssh -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=auto -o ControlPath=/home/vuls-saas/.vuls/cm-eacc137d-%C -o Controlpersist=10m -l Administrator -p 22 -i test -o PasswordAuthentication=no 192.168.0.124
  exitstatus: 1
  stdout:
  stderr: The string is missing the terminator: ".
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString


  err: %!s(<nil>)
[Jan 24 10:00:17] DEBUG [localhost] Executing... systeminfo.exe
[Jan 24 10:00:18] DEBUG [localhost] execResult: servername: windowsserver
  cmd: /usr/bin/ssh -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=auto -o ControlPath=/home/vuls-saas/.vuls/cm-eacc137d-%C -o Controlpersist=10m -l Administrator -p 22 -i test -o PasswordAuthentication=no 192.168.0.124
  exitstatus: 1
  stdout:
  stderr: The string is missing the terminator: ".
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString


  err: %!s(<nil>)
[Jan 24 10:00:18] DEBUG [localhost] Executing... ls /etc/debian_version
[Jan 24 10:00:18] DEBUG [localhost] execResult: servername: windowsserver
  cmd: /usr/bin/ssh -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=auto -o ControlPath=/home/vuls-saas/.vuls/cm-eacc137d-%C -o Controlpersist=10m -l Administrator -p 22 -i test -o PasswordAuthentication=no 192.168.0.124
  exitstatus: 1
  stdout:
  stderr: stty : The term 'stty' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:1
+ stty cols 1000; ls /etc/debian_version
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (stty:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

ls : Cannot find path 'C:\etc\debian_version' because it does not exist.
At line:1 char:17
+ stty cols 1000; ls /etc/debian_version
+                 ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\etc\debian_version:String) [Get-ChildItem], Item
   NotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand


  err: %!s(<nil>)
[Jan 24 10:00:18] DEBUG [localhost] Not Debian like Linux. execResult: servername: windowsserver
  cmd: /usr/bin/ssh -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=auto -o ControlPath=/home/vuls-saas/.vuls/cm-eacc137d-%C -o Controlpersist=10m -l Administrator -p 22 -i test -o PasswordAuthentication=no 192.168.0.124
  exitstatus: 1
  stdout:
  stderr: stty : The term 'stty' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:1
+ stty cols 1000; ls /etc/debian_version
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (stty:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

ls : Cannot find path 'C:\etc\debian_version' because it does not exist.
At line:1 char:17
+ stty cols 1000; ls /etc/debian_version
+                 ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\etc\debian_version:String) [Get-ChildItem], Item
   NotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand


  err: %!s(<nil>)
[Jan 24 10:00:18] DEBUG [localhost] Executing... ls /etc/fedora-release
[Jan 24 10:00:19] DEBUG [localhost] execResult: servername: windowsserver
  cmd: /usr/bin/ssh -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=auto -o ControlPath=/home/vuls-saas/.vuls/cm-eacc137d-%C -o Controlpersist=10m -l Administrator -p 22 -i test -o PasswordAuthentication=no 192.168.0.124
  exitstatus: 1
  stdout:
  stderr: stty : The term 'stty' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:1
+ stty cols 1000; ls /etc/fedora-release
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (stty:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

ls : Cannot find path 'C:\etc\fedora-release' because it does not exist.
At line:1 char:17
+ stty cols 1000; ls /etc/fedora-release
+                 ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\etc\fedora-release:String) [Get-ChildItem], Item
   NotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand


  err: %!s(<nil>)
[Jan 24 10:00:19] DEBUG [localhost] Executing... ls /etc/oracle-release
[Jan 24 10:00:20] DEBUG [localhost] execResult: servername: windowsserver
  cmd: /usr/bin/ssh -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=auto -o ControlPath=/home/vuls-saas/.vuls/cm-eacc137d-%C -o Controlpersist=10m -l Administrator -p 22 -i test -o PasswordAuthentication=no 192.168.0.124
  exitstatus: 1
  stdout:
  stderr: stty : The term 'stty' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:1
+ stty cols 1000; ls /etc/oracle-release
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (stty:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

ls : Cannot find path 'C:\etc\oracle-release' because it does not exist.
At line:1 char:17
+ stty cols 1000; ls /etc/oracle-release
+                 ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\etc\oracle-release:String) [Get-ChildItem], Item
   NotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand


  err: %!s(<nil>)
[Jan 24 10:00:20] DEBUG [localhost] Executing... ls /etc/almalinux-release
[Jan 24 10:00:20] DEBUG [localhost] execResult: servername: windowsserver
  cmd: /usr/bin/ssh -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=auto -o ControlPath=/home/vuls-saas/.vuls/cm-eacc137d-%C -o Controlpersist=10m -l Administrator -p 22 -i test -o PasswordAuthentication=no 192.168.0.124
  exitstatus: 1
  stdout:
  stderr: stty : The term 'stty' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:1
+ stty cols 1000; ls /etc/almalinux-release
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (stty:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

ls : Cannot find path 'C:\etc\almalinux-release' because it does not exist.
At line:1 char:17
+ stty cols 1000; ls /etc/almalinux-release
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\etc\almalinux-release:String) [Get-ChildItem], I
   temNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand


  err: %!s(<nil>)
[Jan 24 10:00:20] DEBUG [localhost] Executing... ls /etc/rocky-release
[Jan 24 10:00:21] DEBUG [localhost] execResult: servername: windowsserver
  cmd: /usr/bin/ssh -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=auto -o ControlPath=/home/vuls-saas/.vuls/cm-eacc137d-%C -o Controlpersist=10m -l Administrator -p 22 -i test -o PasswordAuthentication=no 192.168.0.124
  exitstatus: 1
  stdout:
  stderr: stty : The term 'stty' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:1
+ stty cols 1000; ls /etc/rocky-release
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (stty:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

ls : Cannot find path 'C:\etc\rocky-release' because it does not exist.
At line:1 char:17
+ stty cols 1000; ls /etc/rocky-release
+                 ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\etc\rocky-release:String) [Get-ChildItem], ItemN
   otFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand


  err: %!s(<nil>)
[Jan 24 10:00:21] DEBUG [localhost] Executing... ls /etc/centos-release
[Jan 24 10:00:21] DEBUG [localhost] execResult: servername: windowsserver
  cmd: /usr/bin/ssh -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=auto -o ControlPath=/home/vuls-saas/.vuls/cm-eacc137d-%C -o Controlpersist=10m -l Administrator -p 22 -i test -o PasswordAuthentication=no 192.168.0.124
  exitstatus: 1
  stdout:
  stderr: stty : The term 'stty' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:1
+ stty cols 1000; ls /etc/centos-release
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (stty:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

ls : Cannot find path 'C:\etc\centos-release' because it does not exist.
At line:1 char:17
+ stty cols 1000; ls /etc/centos-release
+                 ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\etc\centos-release:String) [Get-ChildItem], Item
   NotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand


  err: %!s(<nil>)
[Jan 24 10:00:21] DEBUG [localhost] Executing... ls /etc/amazon-linux-release
[Jan 24 10:00:22] DEBUG [localhost] execResult: servername: windowsserver
  cmd: /usr/bin/ssh -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=auto -o ControlPath=/home/vuls-saas/.vuls/cm-eacc137d-%C -o Controlpersist=10m -l Administrator -p 22 -i test -o PasswordAuthentication=no 192.168.0.124
  exitstatus: 1
  stdout:
  stderr: stty : The term 'stty' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:1
+ stty cols 1000; ls /etc/amazon-linux-release
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (stty:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

ls : Cannot find path 'C:\etc\amazon-linux-release' because it does not exist.
At line:1 char:17
+ stty cols 1000; ls /etc/amazon-linux-release
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\etc\amazon-linux-release:String) [Get-ChildItem]
   , ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand


  err: %!s(<nil>)
[Jan 24 10:00:22] DEBUG [localhost] Executing... ls /etc/redhat-release
[Jan 24 10:00:22] DEBUG [localhost] execResult: servername: windowsserver
  cmd: /usr/bin/ssh -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=auto -o ControlPath=/home/vuls-saas/.vuls/cm-eacc137d-%C -o Controlpersist=10m -l Administrator -p 22 -i test -o PasswordAuthentication=no 192.168.0.124
  exitstatus: 1
  stdout:
  stderr: stty : The term 'stty' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:1
+ stty cols 1000; ls /etc/redhat-release
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (stty:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

ls : Cannot find path 'C:\etc\redhat-release' because it does not exist.
At line:1 char:17
+ stty cols 1000; ls /etc/redhat-release
+                 ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\etc\redhat-release:String) [Get-ChildItem], Item
   NotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand


  err: %!s(<nil>)
[Jan 24 10:00:22] DEBUG [localhost] Executing... ls /etc/system-release
[Jan 24 10:00:23] DEBUG [localhost] execResult: servername: windowsserver
  cmd: /usr/bin/ssh -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=auto -o ControlPath=/home/vuls-saas/.vuls/cm-eacc137d-%C -o Controlpersist=10m -l Administrator -p 22 -i test -o PasswordAuthentication=no 192.168.0.124
  exitstatus: 1
  stdout:
  stderr: stty : The term 'stty' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:1
+ stty cols 1000; ls /etc/system-release
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (stty:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

ls : Cannot find path 'C:\etc\system-release' because it does not exist.
At line:1 char:17
+ stty cols 1000; ls /etc/system-release
+                 ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\etc\system-release:String) [Get-ChildItem], Item
   NotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand


  err: %!s(<nil>)
[Jan 24 10:00:23] DEBUG [localhost] Not RedHat like Linux. servername: windowsserver
[Jan 24 10:00:23] DEBUG [localhost] Executing... ls /etc/os-release
[Jan 24 10:00:23] DEBUG [localhost] execResult: servername: windowsserver
  cmd: /usr/bin/ssh -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=auto -o ControlPath=/home/vuls-saas/.vuls/cm-eacc137d-%C -o Controlpersist=10m -l Administrator -p 22 -i test -o PasswordAuthentication=no 192.168.0.124
  exitstatus: 1
  stdout:
  stderr: stty : The term 'stty' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:1
+ stty cols 1000; ls /etc/os-release
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (stty:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

ls : Cannot find path 'C:\etc\os-release' because it does not exist.
At line:1 char:17
+ stty cols 1000; ls /etc/os-release
+                 ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\etc\os-release:String) [Get-ChildItem], ItemNotF
   oundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand


  err: %!s(<nil>)
[Jan 24 10:00:23] DEBUG [localhost] Executing... ls /etc/SuSE-release
[Jan 24 10:00:24] DEBUG [localhost] execResult: servername: windowsserver
  cmd: /usr/bin/ssh -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=auto -o ControlPath=/home/vuls-saas/.vuls/cm-eacc137d-%C -o Controlpersist=10m -l Administrator -p 22 -i test -o PasswordAuthentication=no 192.168.0.124
  exitstatus: 1
  stdout:
  stderr: stty : The term 'stty' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:1
+ stty cols 1000; ls /etc/SuSE-release
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (stty:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

ls : Cannot find path 'C:\etc\SuSE-release' because it does not exist.
At line:1 char:17
+ stty cols 1000; ls /etc/SuSE-release
+                 ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\etc\SuSE-release:String) [Get-ChildItem], ItemNo
   tFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand


  err: %!s(<nil>)
[Jan 24 10:00:24] DEBUG [localhost] Not SUSE Linux. servername: windowsserver
[Jan 24 10:00:24] DEBUG [localhost] Executing... uname
[Jan 24 10:00:24] DEBUG [localhost] execResult: servername: windowsserver
  cmd: /usr/bin/ssh -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=auto -o ControlPath=/home/vuls-saas/.vuls/cm-eacc137d-%C -o Controlpersist=10m -l Administrator -p 22 -i test -o PasswordAuthentication=no 192.168.0.124
  exitstatus: 1
  stdout:
  stderr: stty : The term 'stty' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:1
+ stty cols 1000; uname
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (stty:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

uname : The term 'uname' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:17
+ stty cols 1000; uname
+                 ~~~~~
    + CategoryInfo          : ObjectNotFound: (uname:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


  err: %!s(<nil>)
[Jan 24 10:00:24] DEBUG [localhost] Not FreeBSD. servernam: windowsserver
[Jan 24 10:00:24] DEBUG [localhost] Executing... ls /etc/alpine-release
[Jan 24 10:00:25] DEBUG [localhost] execResult: servername: windowsserver
  cmd: /usr/bin/ssh -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=auto -o ControlPath=/home/vuls-saas/.vuls/cm-eacc137d-%C -o Controlpersist=10m -l Administrator -p 22 -i test -o PasswordAuthentication=no 192.168.0.124
  exitstatus: 1
  stdout:
  stderr: stty : The term 'stty' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:1
+ stty cols 1000; ls /etc/alpine-release
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (stty:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

ls : Cannot find path 'C:\etc\alpine-release' because it does not exist.
At line:1 char:17
+ stty cols 1000; ls /etc/alpine-release
+                 ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\etc\alpine-release:String) [Get-ChildItem], Item
   NotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand


  err: %!s(<nil>)
[Jan 24 10:00:25] DEBUG [localhost] Executing... sw_vers
[Jan 24 10:00:25] DEBUG [localhost] execResult: servername: windowsserver
  cmd: /usr/bin/ssh -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=auto -o ControlPath=/home/vuls-saas/.vuls/cm-eacc137d-%C -o Controlpersist=10m -l Administrator -p 22 -i test -o PasswordAuthentication=no 192.168.0.124
  exitstatus: 1
  stdout:
  stderr: stty : The term 'stty' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:1
+ stty cols 1000; sw_vers
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (stty:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

sw_vers : The term 'sw_vers' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
At line:1 char:17
+ stty cols 1000; sw_vers
+                 ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (sw_vers:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


  err: %!s(<nil>)
[Jan 24 10:00:25] ERROR [localhost] (1/1) Failed: windowsserver, err: [Unknown OS Type:
    github.com/future-architect/vuls/scanner.Scanner.detectOS
        /home/runner/work/futurevuls-backend/futurevuls-backend/scanner-src/scanner/scanner.go:800]
[Jan 24 10:00:25] ERROR [localhost] Failed to scan: Failed to init servers. err:
    github.com/future-architect/vuls/scanner.Scanner.Scan
        /home/runner/work/futurevuls-backend/futurevuls-backend/scanner-src/scanner/scanner.go:93
  - No scannable host OS:
    github.com/future-architect/vuls/scanner.Scanner.initServers
        /home/runner/work/futurevuls-backend/futurevuls-backend/scanner-src/scanner/scanner.go:300
[vuls-saas@ip-192-168-0-136 vuls-saas]$
```
Please re-run the command using ```-debug``` and provide the output below.

# Steps to reproduce the behaviour
Set up public key authentication with Linux as SSH client and Windows as SSH server, and perform remote scan from linux side.

# Configuration (**MUST** fill this out):
Amazon Linux
Windows 10
* Go version (`go version`):

* Go environment (`go env`):

* Vuls environment:
v0.24.8
Hash : ____

To check the commit hash of HEAD
$ vuls -v

or

$ cd $GOPATH/src/github.com/future-architect/vuls 
$ git rev-parse --short HEAD 

* config.toml:
```
# See README for details: https://vuls.io/docs/en/usage-settings.html

version = "v2"

[saas]
  GroupID = xxxx
  Token = "xxxx"
  URL = "https://auth.vuls.biz/one-time-auth"

[default]

[servers]

  [servers.windowsserver]
    user = "Administrator"
    host = "192.168.0.124"
    port = "22"
    keyPath = "test"
    [servers.windowsserver.windows]
    serverSelection = 2
```
* command:
`./vuls scan --debug`

### PR DESCRIPTION
**Pull request by MaineK00n**
# What did you implement:

Fixes #1835 

The issue of failing to identify the OS when the default shell when connecting via SSH is powershell.exe will be fixed by identifying the shell that executes the command and reviewing the escaping of each command.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
### before
```console
$ vuls scan
[Feb  2 12:10:40]  INFO [localhost] vuls-0.24.8-bbf53c7639b266e3a658e8f0a8b2ff7bf17e8e62-2023-12-17T20:41:46Z
[Feb  2 12:10:40]  INFO [localhost] Start scanning
[Feb  2 12:10:40]  INFO [localhost] config: /home/mainek00n/github/github.com/MaineK00n/vuls/config.toml
[Feb  2 12:10:40]  INFO [localhost] Validating config...
[Feb  2 12:10:40]  INFO [localhost] Detecting Server/Container OS... 
[Feb  2 12:10:40]  INFO [localhost] Detecting OS of servers... 
[Feb  2 12:10:44]  INFO [localhost] (1/1) Detected: vagrant: windows Windows Server 2022
[Feb  2 12:10:44]  INFO [localhost] Detecting OS of containers... 
[Feb  2 12:10:44]  INFO [localhost] Checking Scan Modes... 
[Feb  2 12:10:44]  INFO [localhost] Detecting Platforms... 
[Feb  2 12:10:55]  INFO [localhost] (1/1) vagrant is running on other


Scan Summary
================
vagrant	windowsWindows Server 2022	5 installed, 0 updatable





To view the detail, vuls tui is useful.
To send a report, run vuls report -h.
```

### after
```console
$ vuls scan
[Feb  2 12:08:19]  INFO [localhost] vuls-v0.24.8-build-20240202_114014_a865324
[Feb  2 12:08:19]  INFO [localhost] Start scanning
[Feb  2 12:08:19]  INFO [localhost] config: /home/mainek00n/github/github.com/MaineK00n/vuls/config.toml
[Feb  2 12:08:19]  INFO [localhost] Validating config...
[Feb  2 12:08:19]  INFO [localhost] Detecting Server/Container OS... 
[Feb  2 12:08:19]  INFO [localhost] Detecting OS of servers... 
[Feb  2 12:08:22]  INFO [localhost] (1/1) Detected: vagrant: windows Windows Server 2022
[Feb  2 12:08:22]  INFO [localhost] Detecting OS of containers... 
[Feb  2 12:08:22]  INFO [localhost] Checking Scan Modes... 
[Feb  2 12:08:22]  INFO [localhost] Detecting Platforms... 
[Feb  2 12:08:24]  INFO [localhost] (1/1) vagrant is running on other


Scan Summary
================
vagrant	windowsWindows Server 2022	5 installed, 0 updatable





To view the detail, vuls tui is useful.
To send a report, run vuls report -h.
```

### before
```console
$ vuls scan
[Feb  2 12:11:41]  INFO [localhost] vuls-0.24.8-bbf53c7639b266e3a658e8f0a8b2ff7bf17e8e62-2023-12-17T20:41:46Z
[Feb  2 12:11:41]  INFO [localhost] Start scanning
[Feb  2 12:11:41]  INFO [localhost] config: /home/mainek00n/github/github.com/MaineK00n/vuls/config.toml
[Feb  2 12:11:41]  INFO [localhost] Validating config...
[Feb  2 12:11:41]  INFO [localhost] Detecting Server/Container OS... 
[Feb  2 12:11:41]  INFO [localhost] Detecting OS of servers... 
[Feb  2 12:12:32] ERROR [localhost] (1/1) Failed: vagrant, err: [Unknown OS Type:
    github.com/future-architect/vuls/scanner.Scanner.detectOS
        /home/runner/work/vuls/vuls/scanner/scanner.go:800]
[Feb  2 12:12:32] ERROR [localhost] Failed to scan: Failed to init servers. err:
    github.com/future-architect/vuls/scanner.Scanner.Scan
        /home/runner/work/vuls/vuls/scanner/scanner.go:93
  - No scannable host OS:
    github.com/future-architect/vuls/scanner.Scanner.initServers
        /home/runner/work/vuls/vuls/scanner/scanner.go:300
```

### after
```console
$ vuls scan
[Feb  2 12:13:11]  INFO [localhost] vuls-v0.24.8-build-20240202_114014_a865324
[Feb  2 12:13:11]  INFO [localhost] Start scanning
[Feb  2 12:13:11]  INFO [localhost] config: /home/mainek00n/github/github.com/MaineK00n/vuls/config.toml
[Feb  2 12:13:11]  INFO [localhost] Validating config...
[Feb  2 12:13:11]  INFO [localhost] Detecting Server/Container OS... 
[Feb  2 12:13:11]  INFO [localhost] Detecting OS of servers... 
[Feb  2 12:13:17]  INFO [localhost] (1/1) Detected: vagrant: windows Windows Server 2022
[Feb  2 12:13:17]  INFO [localhost] Detecting OS of containers... 
[Feb  2 12:13:17]  INFO [localhost] Checking Scan Modes... 
[Feb  2 12:13:17]  INFO [localhost] Detecting Platforms... 
[Feb  2 12:13:34]  INFO [localhost] (1/1) vagrant is running on other


Scan Summary
================
vagrant	windowsWindows Server 2022	5 installed, 0 updatable





To view the detail, vuls tui is useful.
To send a report, run vuls report -h.
```

### before
```console
vagrant@WIN-HL763J091HK C:\Users\vagrant>vuls.exe scan
time="Feb  2 03:03:13" level=info msg="vuls-0.24.8-bbf53c7639b266e3a658e8f0a8b2ff7bf17e8e62-2023-12-17T20:41:46Z" 
time="Feb  2 03:03:13" level=info msg="Start scanning" 
time="Feb  2 03:03:13" level=info msg="config: C:\\Users\\vagrant\\config.toml" 
time="Feb  2 03:03:13" level=info msg="Validating config..." 
time="Feb  2 03:03:13" level=info msg="Detecting Server/Container OS... " 
time="Feb  2 03:03:13" level=info msg="Detecting OS of servers... " 
time="Feb  2 03:03:17" level=info msg="(1/1) Detected: localhost: windows Windows Server 2022" 
time="Feb  2 03:03:17" level=info msg="Detecting OS of containers... " 
time="Feb  2 03:03:17" level=info msg="Checking Scan Modes... " 
time="Feb  2 03:03:17" level=info msg="Detecting Platforms... " 
time="Feb  2 03:03:27" level=info msg="(1/1) localhost is running on other" 


Scan Summary
================
localhost       windowsWindows Server 2022      5 installed, 0 updatable





To view the detail, vuls tui is useful.
To send a report, run vuls report -h.
```

### after
```console
vagrant@WIN-HL763J091HK C:\Users\vagrant>vuls.exe scan
time="Feb  2 02:59:33" level=info msg="vuls-v0.24.8-build-20240202_114712_a865324" 
time="Feb  2 02:59:33" level=info msg="Start scanning" 
time="Feb  2 02:59:33" level=info msg="config: C:\\Users\\vagrant\\config.toml" 
time="Feb  2 02:59:33" level=info msg="Validating config..." 
time="Feb  2 02:59:33" level=info msg="Detecting Server/Container OS... " 
time="Feb  2 02:59:33" level=info msg="Detecting OS of servers... " 
time="Feb  2 02:59:42" level=info msg="(1/1) Detected: localhost: windows Windows Server 2022" 
time="Feb  2 02:59:42" level=info msg="Detecting OS of containers... " 
time="Feb  2 02:59:42" level=info msg="Checking Scan Modes... " 
time="Feb  2 02:59:42" level=info msg="Detecting Platforms... " 
time="Feb  2 02:59:59" level=info msg="(1/1) localhost is running on other" 


Scan Summary
================
localhost       windowsWindows Server 2022      5 installed, 0 updatable





To view the detail, vuls tui is useful.
To send a report, run vuls report -h.
```

### before
```console
PS C:\Users\vagrant> .\vuls.exe scan
time="Feb  2 03:06:34" level=info msg="vuls-0.24.8-bbf53c7639b266e3a658e8f0a8b2ff7bf17e8e62-2023-12-17T20:41:46Z" 
time="Feb  2 03:06:34" level=info msg="Start scanning" 
time="Feb  2 03:06:34" level=info msg="config: C:\\Users\\vagrant\\config.toml"
time="Feb  2 03:06:34" level=info msg="Validating config..."
time="Feb  2 03:06:34" level=info msg="Detecting Server/Container OS... "
time="Feb  2 03:06:34" level=info msg="Detecting OS of servers... "
time="Feb  2 03:06:38" level=info msg="(1/1) Detected: localhost: windows Windows Server 2022" 
time="Feb  2 03:06:38" level=info msg="Detecting OS of containers... " 
time="Feb  2 03:06:38" level=info msg="Checking Scan Modes... "
time="Feb  2 03:06:38" level=info msg="Detecting Platforms... "
time="Feb  2 03:06:50" level=info msg="(1/1) localhost is running on other" 


Scan Summary
================
localhost       windowsWindows Server 2022      5 installed, 0 updatable





To view the detail, vuls tui is useful.
To send a report, run vuls report -h.
```

### after
```console
PS C:\Users\vagrant> .\vuls.exe scan
time="Feb  2 03:04:54" level=info msg="vuls-v0.24.8-build-20240202_114712_a865324" 
time="Feb  2 03:04:54" level=info msg="Start scanning" 
time="Feb  2 03:04:54" level=info msg="config: C:\\Users\\vagrant\\config.toml"
time="Feb  2 03:04:54" level=info msg="Validating config..."
time="Feb  2 03:04:54" level=info msg="Detecting Server/Container OS... "
time="Feb  2 03:04:54" level=info msg="Detecting OS of servers... "
time="Feb  2 03:04:58" level=info msg="(1/1) Detected: localhost: windows Windows Server 2022" 
time="Feb  2 03:04:58" level=info msg="Detecting OS of containers... " 
time="Feb  2 03:04:58" level=info msg="Checking Scan Modes... "
time="Feb  2 03:04:58" level=info msg="Detecting Platforms... "
time="Feb  2 03:05:11" level=info msg="(1/1) localhost is running on other" 


Scan Summary
================
localhost       windowsWindows Server 2022      5 installed, 0 updatable





To view the detail, vuls tui is useful.
To send a report, run vuls report -h.
```
# Checklist:
You don't have to satisfy all of the following.

- [x] Write tests
- [ ] Write documentation
- [x] Check that there aren't other open pull requests for the same issue/feature
- [x] Format your source code by `make fmt`
- [x] Pass the test by `make test`
- [x] Provide verification config / commands
- [x] Enable "Allow edits from maintainers" for this PR
- [x] Update the messages below

***Is this ready for review?:*** YES

# Reference

### CODE REVIEW

File: scanner/windows.go [hunk 1]
```diff
@@ -50,30 +52,60 @@ func newWindows(c config.ServerInfo) *windows {
...
+			switch strings.TrimSpace(r.Stdout) {
+			case "$env:OS":
+				return "cmd.exe"
+			case "Windows_NT":
+				return "powershell"
+			default:
+				if rr := w.exec("Get-ChildItem env:OS", noSudo); rr.isSuccess() {
+					return "powershell"
+				}
+				return "unknown"
```
Comment (shino) [inline scanner/windows.go:67]: I guess this is not normal case, how about adding log line with echo and Get-ChildItem outputs ?
It might help us debugging in the future.

File: scanner/windows.go [hunk 2]
```diff
@@ -50,30 +52,60 @@ func newWindows(c config.ServerInfo) *windows {
...
 			}
+		}
+		return "unknown"
```
Comment (shino) [inline scanner/windows.go:70]: Is it good to proceed in this case? Hmm... Better to just exit with error message of ssh?

File: scanner/windows.go (hunk 1 above)
Comment (shino) [reply scanner/windows.go:67]: My bad. This is the case for bash and such shells, isn't it? Looks nice!

File: scanner/windows.go (hunk 2 above)
Comment (shino) [reply scanner/windows.go:70]: It's good. No treatment needed!

**Review by shino — APPROVED** [review]
:confetti_ball:
